#!/usr/bin/env Rscript
# Frozen-protocol V9: one certified-input union scan; no allele transformation.
options(stringsAsFactors = FALSE, warn = 1)
pkgs <- c("digest", "DBI", "duckdb", "jsonlite")
if (any(!vapply(pkgs, requireNamespace, logical(1), quietly = TRUE))) stop("Required installed package missing; no automatic installation.", call. = FALSE)
args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 2L || args[[1L]] != "--project-root") stop("Usage: Rscript.exe R/05_extract_finngen_r13_outcomes_v9.R --project-root E:/Research/hb_delirium_bidir_mr", call. = FALSE)
root <- normalizePath(args[[2L]], winslash = "/", mustWork = TRUE)
stop_if <- function(x, m) if (isTRUE(x)) stop(m, call. = FALSE)
hash_file <- function(p) digest::digest(file = p, algo = "sha256", serialize = FALSE)
validate_sha_literal <- function(x, label) { x <- tolower(trimws(as.character(x))); stop_if(length(x) != 1L || nchar(x, type = "chars") != 64L || !grepl("^[0-9a-f]{64}$", x), paste0("Invalid frozen SHA-256 literal: ", label)); x }
sql_path <- function(p) gsub("'", "''", normalizePath(p, winslash = "/", mustWork = TRUE), fixed = TRUE)
strict_num <- function(x, label) { raw <- trimws(as.character(x)); miss <- is.na(raw) | raw %in% c("", "NA", "."); y <- suppressWarnings(as.numeric(ifelse(miss, NA_character_, raw))); stop_if(any(!miss & is.na(y)), paste("Numeric conversion failed:", label)); y }
comp <- function(x) unname(c(A = "T", T = "A", C = "G", G = "C")[x])
setkey <- function(a, b) paste(sort(c(a, b)), collapse = "/")
fg <- file.path(root, "data_raw", "gwas", "finngen_R13_F5_DELIRIUM.gz")
cert_path <- file.path(root, "results", "qc", "finngen_R13_F5_DELIRIUM_input_certification_v1.json")
inc_path <- file.path(root, "data_derived", "instruments", "vuckovic_hb_instruments_apoe_included_v2.tsv")
exc_path <- file.path(root, "data_derived", "instruments", "vuckovic_hb_instruments_apoe_excluded_v2.tsv")
expected_fg_sha <- validate_sha_literal("85637f0f3358807964d4f8a3e500293168a706f1c08c65f3fc5512b65df40ed8", "expected_fg_sha")
expected_cert_sha <- validate_sha_literal("a1eb1fb19020af740891d291ec00032e72c3e25978f67ae0612af34a5b547b1f", "expected_cert_sha")
expected_inc_sha <- validate_sha_literal("2d8b2c9c864dd571a8d81b78583e6f5845eb78ff207ab481467d75ab58fee2b8", "expected_inc_sha")
expected_exc_sha <- validate_sha_literal("5cf6940d05548696bd12d5a33fa9c215a7204d11c5075ed734e2e4a624768e8d", "expected_exc_sha")
header <- c("#chrom", "pos", "ref", "alt", "rsids", "nearest_genes", "pval", "mlogp", "beta", "sebeta", "af_alt", "af_alt_cases", "af_alt_controls")
out <- c(target_union = file.path(root,"data_derived","outcome_extracts","vuckovic_hb_target_union_v9.parquet"), union_matches = file.path(root,"data_derived","outcome_extracts","vuckovic_hb_finngen_r13_union_matches_v9.parquet"), inc_pq = file.path(root,"data_derived","outcome_extracts","vuckovic_hb_finngen_r13_apoe_included_v9.parquet"), inc_tsv = file.path(root,"data_derived","outcome_extracts","vuckovic_hb_finngen_r13_apoe_included_v9.tsv"), exc_pq = file.path(root,"data_derived","outcome_extracts","vuckovic_hb_finngen_r13_apoe_excluded_v9.parquet"), exc_tsv = file.path(root,"data_derived","outcome_extracts","vuckovic_hb_finngen_r13_apoe_excluded_v9.tsv"), missing = file.path(root,"data_derived","outcome_extracts","audit","vuckovic_hb_finngen_r13_missing_v9.parquet"), multiple = file.path(root,"data_derived","outcome_extracts","audit","vuckovic_hb_finngen_r13_multiple_matches_v9.parquet"), allele = file.path(root,"data_derived","outcome_extracts","audit","vuckovic_hb_finngen_r13_allele_audit_v9.parquet"), qc = file.path(root,"results","qc","vuckovic_hb_finngen_r13_extraction_v9.json"), match_csv = file.path(root,"results","qc","vuckovic_hb_finngen_r13_match_counts_v9.csv"), allele_csv = file.path(root,"results","qc","vuckovic_hb_finngen_r13_allele_counts_v9.csv"), log = file.path(root,"results","logs","vuckovic_hb_finngen_r13_extraction_v9.log"))
partial_output_names <- names(out)[names(out) != "log"]
partials <- setNames(paste0(unname(out[partial_output_names]), ".partial"), partial_output_names)
log_created <- FALSE
log_line <- function(x) cat(sprintf("%s %s\n", format(Sys.time(), "%Y-%m-%dT%H:%M:%S%z"), x), file = out[["log"]], append = TRUE)
safe_log_line <- function(x) if (isTRUE(log_created)) try(log_line(x), silent = TRUE)
read_gzip_header_once <- function(path) { con <- gzfile(path, open = "rt", encoding = "UTF-8"); tryCatch(readLines(con, n = 1L, warn = TRUE), finally = { cleanup_error <- tryCatch({ close(con); NULL }, error = function(e) e); if (inherits(cleanup_error, "error")) safe_log_line(paste0("CLEANUP_WARNING: gzip header connection close: ", conditionMessage(cleanup_error))) }) }
safe_db_disconnect <- function(con) { if (is.null(con)) return(invisible(NULL)); tryCatch(withCallingHandlers({ if (DBI::dbIsValid(con)) DBI::dbDisconnect(con, shutdown = TRUE) }, warning = function(w) { safe_log_line(paste0("CLEANUP_WARNING: DuckDB disconnect: ", conditionMessage(w))); invokeRestart("muffleWarning") }), error = function(e) safe_log_line(paste0("CLEANUP_WARNING: DuckDB disconnect: ", conditionMessage(e)))); invisible(NULL) }
safe_cleanup_partials <- function(paths) { for (p in paths[file.exists(paths)]) tryCatch({ status <- unlink(p, force = FALSE); if (!identical(status, 0L) && file.exists(p)) stop("unlink returned a non-zero status", call. = FALSE) }, error = function(e) safe_log_line(paste0("CLEANUP_WARNING: partial cleanup for ", p, ": ", conditionMessage(e)))); invisible(NULL) }

# Counts formal SQL source declarations only; it is not a physical-scan estimate.
count_sql_source_calls <- function(sql) {
  hits <- gregexpr("read_csv\\s*\\(", tolower(sql), perl = TRUE)[[1L]]
  if (length(hits) == 1L && hits[[1L]] == -1L) return(0L)
  length(hits)
}
# This is the only union-query builder. Formal execution and SQL tests call it identically.
build_union_query <- function(source_sql, target_rsids) {
  stop_if(length(target_rsids) < 1L || any(!grepl("^rs[0-9]+$", target_rsids)), "Target rsID list invalid for exact-token query.")
  vals <- paste(sprintf("'%s'", target_rsids), collapse = ", ")
  sprintf("WITH raw AS (SELECT row_number() OVER() scan_row_number, \"#chrom\" fg_chrom,pos fg_pos,ref fg_ref,alt fg_alt,rsids fg_rsids_raw,nearest_genes fg_nearest_genes,pval fg_pval_raw,mlogp fg_mlogp_raw,beta fg_beta_raw,sebeta fg_se_raw,af_alt fg_af_alt_raw,af_alt_cases fg_af_alt_cases_raw,af_alt_controls fg_af_alt_controls_raw, COUNT(*) OVER() observed_data_rows, SUM(CASE WHEN trim(coalesce(rsids,''))='' THEN 1 ELSE 0 END) OVER() missing_rsids_rows, SUM(CASE WHEN instr(coalesce(rsids,''),',')>0 AND instr(coalesce(rsids,''),';')=0 THEN 1 ELSE 0 END) OVER() comma_delimited_rows, SUM(CASE WHEN instr(coalesce(rsids,''),';')>0 AND instr(coalesce(rsids,''),',')=0 THEN 1 ELSE 0 END) OVER() semicolon_delimited_rows, SUM(CASE WHEN instr(coalesce(rsids,''),';')>0 AND instr(coalesce(rsids,''),',')>0 THEN 1 ELSE 0 END) OVER() mixed_delimiter_rows, SUM(CASE WHEN trim(coalesce(rsids,''))<>'' AND NOT regexp_full_match(trim(coalesce(rsids,'')),'^rs[0-9]+([[:space:]]*[,;][[:space:]]*rs[0-9]+)*$') THEN 1 ELSE 0 END) OVER() noncanonical_rsids_rows FROM %s), tok AS (SELECT raw.*,trim(t.token) matched_rsid_token FROM raw CROSS JOIN UNNEST(string_split(replace(coalesce(fg_rsids_raw,''),';',','), ',')) AS t(token)) SELECT *, noncanonical_rsids_rows AS noncanonical_rsids_rows FROM tok WHERE scan_row_number=1 OR matched_rsid_token IN (%s)", source_sql, vals)
}

main <- function() {
  stop_if(any(file.exists(c(out, partials))), "A V9 final or partial target exists; refusing to overwrite.")
  stop_if(any(!file.exists(c(fg, cert_path, inc_path, exc_path))), "Required V9 input missing.")
  dir.create(dirname(out[["target_union"]]), recursive = TRUE, showWarnings = FALSE); dir.create(dirname(out[["missing"]]), recursive = TRUE, showWarnings = FALSE); dir.create(dirname(out[["qc"]]), recursive = TRUE, showWarnings = FALSE); dir.create(dirname(out[["log"]]), recursive = TRUE, showWarnings = FALSE)
  log_created <<- TRUE; log_line("Protocol=docs/protocol/analysis_plan_v1.1.md; V9 certified-input union extraction."); on.exit(safe_cleanup_partials(partials), add = TRUE)
  cert_sha <- hash_file(cert_path); stop_if(!identical(cert_sha, expected_cert_sha), "Certification JSON SHA-256 mismatch; full scan not started.")
  cert <- jsonlite::fromJSON(cert_path, simplifyVector = FALSE); required_cert <- c("certification_status","certified_data_rows","certified_header_rows","certified_physical_lines","certified_input_sha256","expected_sha256","sha256_before","sha256_after","sha256_match_before","sha256_match_after","header_exact_match")
  stop_if(!all(required_cert %in% names(cert)), "Certification JSON missing required gate fields.")
  stop_if(cert$certification_status != "passed" || !isTRUE(cert$header_exact_match) || as.numeric(cert$certified_header_rows) != 1 || as.numeric(cert$certified_physical_lines) != as.numeric(cert$certified_data_rows) + as.numeric(cert$certified_header_rows), "Certification JSON content gate failed.")
  cert_hashes <- tolower(unlist(cert[c("expected_sha256","sha256_before","sha256_after","certified_input_sha256")]))
  stop_if(length(unique(cert_hashes)) != 1L || cert_hashes[[1L]] != expected_fg_sha || !isTRUE(cert$sha256_match_before) || !isTRUE(cert$sha256_match_after), "Certification JSON SHA-content gate failed.")
  fg_sha_before <- hash_file(fg); stop_if(!identical(fg_sha_before, cert_hashes[[1L]]), "Current FinnGen SHA-256 does not match certification; full scan not started."); log_line(sprintf("Certification gate passed: json_sha256=%s; certified_data_rows=%s.", cert_sha, cert$certified_data_rows))
  req <- c("rsid","chr","pos","effect_allele","other_allele","beta","se","eaf","lp_raw","pval","F_stat","apoe_region","source_row_number","variant_id_source","clumping_analysis")
  read_iv <- function(p) { x <- read.delim(p, sep = "\t", header = TRUE, colClasses = "character", check.names = FALSE); stop_if(!identical(names(x), req), "Instrument header mismatch."); stop_if(anyDuplicated(x$rsid) > 0 || any(x$rsid == ""), "Instrument rsID invalid."); x }
  inc <- read_iv(inc_path); exc <- read_iv(exc_path); inc_sha_observed <- hash_file(inc_path); exc_sha_observed <- hash_file(exc_path)
  log_line(sprintf("included_expected_sha=%s; included_observed_sha=%s; included_sha_match=%s", expected_inc_sha, inc_sha_observed, identical(inc_sha_observed, expected_inc_sha))); log_line(sprintf("excluded_expected_sha=%s; excluded_observed_sha=%s; excluded_sha_match=%s", expected_exc_sha, exc_sha_observed, identical(exc_sha_observed, expected_exc_sha)))
  stop_if(!identical(inc_sha_observed, expected_inc_sha) || !identical(exc_sha_observed, expected_exc_sha), "Instrument SHA-256 mismatch.")
  shared <- intersect(inc$rsid, exc$rsid); stop_if(nrow(inc) != 393L || nrow(exc) != 394L || length(shared) != 392L || length(union(inc$rsid, exc$rsid)) != 395L, "Frozen instrument-set count gate failed."); stop_if(!identical(sort(setdiff(inc$rsid, exc$rsid)), "rs58324280") || !identical(sort(setdiff(exc$rsid, inc$rsid)), c("rs147804508","rs76511276")), "Frozen instrument-set membership gate failed.")
  fshared <- setdiff(req, "clumping_analysis"); a <- inc[match(sort(shared),inc$rsid),fshared]; b <- exc[match(sort(shared),exc$rsid),fshared]; stop_if(!all(vapply(fshared, function(z) identical(a[[z]],b[[z]]), logical(1))), "Shared exposure fields differ.")
  mkexp <- function(x, ii, ee) data.frame(rsid=x$rsid,in_apoe_included_input=ii,in_apoe_excluded_input=ee,exposure_chr=strict_num(x$chr,"exposure_chr"),exposure_pos=strict_num(x$pos,"exposure_pos"),exposure_effect_allele=toupper(x$effect_allele),exposure_other_allele=toupper(x$other_allele),exposure_beta=strict_num(x$beta,"exposure_beta"),exposure_se=strict_num(x$se,"exposure_se"),exposure_eaf=strict_num(x$eaf,"exposure_eaf"),exposure_lp_raw=strict_num(x$lp_raw,"exposure_lp_raw"),exposure_pval=strict_num(x$pval,"exposure_pval"),exposure_F_stat=strict_num(x$F_stat,"exposure_F_stat"),exposure_apoe_region=toupper(x$apoe_region)=="TRUE",exposure_source_row_number=strict_num(x$source_row_number,"source_row_number"),exposure_variant_id_source=x$variant_id_source,exposure_source="Vuckovic2020_GCST90002384",exposure_trait="hemoglobin",exposure_build="GRCh37",exposure_n_study=408112,exposure_n_variant=NA_real_,exposure_effect_scale="standardized inverse-normal transformed hemoglobin; beta per ALT allele",stringsAsFactors=FALSE)
  target <- mkexp(inc,TRUE,FALSE); target$in_apoe_excluded_input <- target$rsid %in% exc$rsid; target <- rbind(target,mkexp(exc[!exc$rsid %in% inc$rsid,,drop=FALSE],FALSE,TRUE)); target <- target[order(target$rsid),]; rownames(target) <- NULL
  h <- read_gzip_header_once(fg); header_line_count <- length(h); header_observed <- if(header_line_count == 1L) strsplit(h[[1L]], "\t", fixed=TRUE)[[1L]] else character(); header_column_count <- length(header_observed); header_exact_match <- header_line_count == 1L && header_column_count == length(header) && identical(header_observed,header)
  log_line(sprintf("header_line_count=%s",header_line_count)); log_line(sprintf("header_column_count=%s",header_column_count)); log_line(sprintf("header_exact_match=%s",header_exact_match)); log_line(paste0("header_expected=",paste(header,collapse="<TAB>"))); log_line(paste0("header_observed=",if(header_line_count == 1L) gsub("\t","<TAB>",h[[1L]],fixed=TRUE) else paste0("<line_count=",header_line_count,">")))
  stop_if(!(header_line_count == 1L && header_column_count == 13L && isTRUE(header_exact_match)), "Raw FinnGen header gate failed.")
  con <- DBI::dbConnect(duckdb::duckdb(shared_home = FALSE)); on.exit(safe_db_disconnect(con), add = TRUE)
  schema <- paste(sprintf("'%s': 'VARCHAR'",header),collapse=", "); source_sql <- sprintf("read_csv('%s', header=true, delim='\\t', columns={%s}, auto_detect=false, strict_mode=true)",sql_path(fg),schema); q <- build_union_query(source_sql,target$rsid)
  plan <- DBI::dbGetQuery(con,paste("EXPLAIN",q)); plan_text <- paste(unlist(plan),collapse="\n"); explain_status <- "passed"; explain_plan_sha256 <- digest::digest(plan_text,algo="sha256",serialize=FALSE); explain_plan_line_count <- length(strsplit(plan_text,"\n",fixed=TRUE)[[1L]]); formal_query_read_csv_source_calls <- count_sql_source_calls(q); formal_full_query_invocations <- 1L; included_excluded_derived_from_same_union <- TRUE; physical_scan_count_claimed <- FALSE; physical_scan_count <- NA_integer_; stop_if(formal_query_read_csv_source_calls != 1L,"Formal SQL must contain exactly one read_csv source."); log_line("DuckDB_EXPLAIN_STATUS=passed"); log_line(sprintf("formal_query_read_csv_source_calls=%s",formal_query_read_csv_source_calls)); log_line(sprintf("formal_full_query_invocations=%s",formal_full_query_invocations)); log_line("physical_scan_count_claimed=FALSE")
  scan <- DBI::dbGetQuery(con,q); sentinel <- scan[scan$scan_row_number==1L,,drop=FALSE]; stop_if(nrow(sentinel)!=1L,"Scan audit sentinel must be exactly one row."); non_sentinel <- scan[scan$scan_row_number!=1L,,drop=FALSE]; returned_non_target_detail_rows <- sum(!(non_sentinel$matched_rsid_token %in% target$rsid)); returned_target_match_rows <- nrow(non_sentinel); returned_total_rows <- nrow(scan); stop_if(returned_non_target_detail_rows!=0L,"Returned non-target detail rows detected."); observed <- as.numeric(sentinel$observed_data_rows[[1L]]); stop_if(observed != as.numeric(cert$certified_data_rows),"Observed data rows differ from certification; no outputs published.")
  audit <- lapply(as.list(sentinel[c("missing_rsids_rows","comma_delimited_rows","semicolon_delimited_rows","mixed_delimiter_rows","noncanonical_rsids_rows")]),as.numeric); 
  m <- scan[scan$matched_rsid_token %in% target$rsid,,drop=FALSE]; m <- m[!duplicated(m[c("scan_row_number","matched_rsid_token")]),,drop=FALSE]; m$rsid <- m$matched_rsid_token; target$finngen_match_count <- as.integer(table(m$rsid)[target$rsid]); target$finngen_match_count[is.na(target$finngen_match_count)] <- 0L; target$finngen_match_status <- ifelse(target$finngen_match_count==0,"missing_in_finngen",ifelse(target$finngen_match_count==1,"unique_match","multiple_finngen_matches")); matches <- merge(target,m,by="rsid",all.y=TRUE,sort=FALSE); unique_m <- matches[matches$finngen_match_status=="unique_match",,drop=FALSE]; missing_m <- target[target$finngen_match_status=="missing_in_finngen",,drop=FALSE]; multiple_m <- matches[matches$finngen_match_status=="multiple_finngen_matches",,drop=FALSE]; stop_if(nrow(target)!=395L || sum(table(target$finngen_match_status))!=395L || anyDuplicated(unique_m$rsid)>0,"Target classification validation failed.")
  addout <- function(x) { x$outcome_source<-"FinnGen_R13_F5_DELIRIUM"; x$outcome_trait<-"delirium"; x$outcome_build<-"GRCh38"; x$outcome_effect_allele<-toupper(x$fg_alt); x$outcome_other_allele<-toupper(x$fg_ref); x$outcome_rsids_raw<-x$fg_rsids_raw; x$outcome_matched_rsid_token<-x$matched_rsid_token; x$outcome_pos_raw<-x$fg_pos; x$outcome_pval_raw<-x$fg_pval_raw; x$outcome_log10p_raw<-x$fg_mlogp_raw; x$outcome_beta_raw<-x$fg_beta_raw; x$outcome_se_raw<-x$fg_se_raw; x$outcome_af_alt_raw<-x$fg_af_alt_raw; x$outcome_af_alt_cases_raw<-x$fg_af_alt_cases_raw; x$outcome_af_alt_controls_raw<-x$fg_af_alt_controls_raw; x$outcome_pos<-strict_num(x$fg_pos,"outcome_pos"); x$outcome_pval<-strict_num(x$fg_pval_raw,"outcome_pval"); x$outcome_log10p<-strict_num(x$fg_mlogp_raw,"outcome_log10p"); x$outcome_beta<-strict_num(x$fg_beta_raw,"outcome_beta"); x$outcome_se<-strict_num(x$fg_se_raw,"outcome_se"); x$outcome_eaf<-strict_num(x$fg_af_alt_raw,"outcome_af_alt"); x$outcome_ncase<-5121L; x$outcome_ncontrol<-465023L; x$outcome_n_study<-470144L; x$outcome_effect_scale<-"log(OR) for delirium per ALT allele"; x }
  allele <- addout(unique_m); okx <- allele$exposure_effect_allele %in% c("A","C","G","T") & allele$exposure_other_allele %in% c("A","C","G","T"); oko <- allele$outcome_effect_allele %in% c("A","C","G","T") & allele$outcome_other_allele %in% c("A","C","G","T"); allele$exposure_allele_set <- mapply(setkey,allele$exposure_effect_allele,allele$exposure_other_allele); allele$outcome_allele_set <- mapply(setkey,allele$outcome_effect_allele,allele$outcome_other_allele); same <- okx & oko & allele$exposure_allele_set==allele$outcome_allele_set; strand <- okx & oko & allele$exposure_allele_set==mapply(setkey,comp(allele$outcome_effect_allele),comp(allele$outcome_other_allele)); allele$palindromic_snp <- okx & allele$exposure_allele_set %in% c("A/T","C/G"); allele$allele_relation <- ifelse(!okx|!oko,"allele_missing_or_invalid",ifelse(same,"same_unordered_allele_set",ifelse(strand,"strand_complement_match","incompatible_alleles"))); allele$allele_audit_status <- ifelse(allele$palindromic_snp,"palindromic_snp",allele$allele_relation); incout <- allele[allele$rsid %in% inc$rsid,,drop=FALSE]; excout <- allele[allele$rsid %in% exc$rsid,,drop=FALSE]
  writepq <- function(x,p) { nm <- "v9write"; DBI::dbWriteTable(con,nm,x,temporary=TRUE,overwrite=TRUE); DBI::dbExecute(con,sprintf("COPY %s TO '%s' (FORMAT PARQUET)",nm,gsub("'","''",p,fixed=TRUE))); DBI::dbRemoveTable(con,nm) }; writetsv <- function(x,p) write.table(x,p,sep="\t",row.names=FALSE,quote=FALSE,na="")
  pp <- setNames(paste0(unname(out), ".partial"), names(out))
  required_output_keys <- c("target_union","union_matches","inc_pq","inc_tsv","exc_pq","exc_tsv","missing","multiple","allele","qc","match_csv","allele_csv","log")
  stop_if(!identical(names(pp), names(out)), "Partial path names do not exactly match output path names.")
  stop_if(!all(required_output_keys %in% names(pp)), "Partial path map is missing required keys.")
  stop_if(anyNA(pp) || any(pp == ""), "Partial path map contains missing or empty paths."); writepq(target,pp[["target_union"]]); writepq(matches,pp[["union_matches"]]); writepq(incout,pp[["inc_pq"]]); writetsv(incout,pp[["inc_tsv"]]); writepq(excout,pp[["exc_pq"]]); writetsv(excout,pp[["exc_tsv"]]); writepq(missing_m,pp[["missing"]]); writepq(multiple_m,pp[["multiple"]]); writepq(allele,pp[["allele"]]); mc <- as.data.frame(table(target$finngen_match_status)); names(mc) <- c("match_status","target_count"); ac <- as.data.frame(table(allele$allele_audit_status)); names(ac) <- c("allele_audit_status","count"); write.csv(mc,pp[["match_csv"]],row.names=FALSE); write.csv(ac,pp[["allele_csv"]],row.names=FALSE)
  staged_inc_tsv <- read.delim(pp[["inc_tsv"]],check.names=FALSE); staged_exc_tsv <- read.delim(pp[["exc_tsv"]],check.names=FALSE); staged_inc_pq <- DBI::dbGetQuery(con,sprintf("SELECT rsid FROM read_parquet('%s')",sql_path(pp[["inc_pq"]]))); staged_exc_pq <- DBI::dbGetQuery(con,sprintf("SELECT rsid FROM read_parquet('%s')",sql_path(pp[["exc_pq"]]))); stop_if(!setequal(staged_inc_tsv$rsid,incout$rsid)||!setequal(staged_exc_tsv$rsid,excout$rsid)||!setequal(staged_inc_pq$rsid,staged_inc_tsv$rsid)||!setequal(staged_exc_pq$rsid,staged_exc_tsv$rsid),"Parquet/TSV validation failed.")
  fg_sha_after <- hash_file(fg); stop_if(!identical(fg_sha_after,fg_sha_before)||!identical(fg_sha_after,cert_hashes[[1L]]),"FinnGen SHA changed during scan."); output_hashes <- vapply(pp[names(pp) %in% c("target_union","union_matches","inc_pq","inc_tsv","exc_pq","exc_tsv","missing","multiple","allele","match_csv","allele_csv")],hash_file,character(1)); qc <- list(protocol="docs/protocol/analysis_plan_v1.1.md",certification_json_path=cert_path,certification_json_sha256_expected=expected_cert_sha,certification_json_sha256_observed=cert_sha,certification_status=cert$certification_status,certified_data_rows=cert$certified_data_rows,certified_header_rows=cert$certified_header_rows,certified_physical_lines=cert$certified_physical_lines,certified_input_sha256=cert$certified_input_sha256,explain_status=explain_status,explain_plan_sha256=explain_plan_sha256,explain_plan_line_count=explain_plan_line_count,formal_query_read_csv_source_calls=formal_query_read_csv_source_calls,formal_full_query_invocations=formal_full_query_invocations,included_excluded_derived_from_same_union=included_excluded_derived_from_same_union,physical_scan_count_claimed=physical_scan_count_claimed,physical_scan_count=physical_scan_count,observed_data_rows=observed,rsids_audit=audit,returned_total_rows=returned_total_rows,returned_target_match_rows=returned_target_match_rows,returned_non_target_detail_rows=returned_non_target_detail_rows,missing_targets_require_format_diagnostic=any(target$finngen_match_status=="missing_in_finngen"),input_sha256=list(finngen_before=fg_sha_before,finngen_after=fg_sha_after,included=hash_file(inc_path),excluded=hash_file(exc_path)),output_sha256_excluding_qc_json_and_log=output_hashes,match_counts=mc,allele_counts=ac); writeLines(jsonlite::toJSON(qc,auto_unbox=TRUE,pretty=TRUE),pp[["qc"]]); for(n in names(out)[names(out)!="log"]) { stop_if(file.exists(out[[n]]),"Output appeared during run."); stop_if(!file.rename(pp[[n]],out[[n]]),paste("Atomic rename failed",n)) }; log_line(sprintf("SUCCESS: observed_data_rows=%s; formal_query_read_csv_source_calls=%s; formal_full_query_invocations=%s; physical_scan_count_claimed=FALSE.",observed,formal_query_read_csv_source_calls,formal_full_query_invocations))
}
tryCatch(main(), error = function(e) { safe_log_line(paste0("TERMINATED_PRIMARY: ", conditionMessage(e))); quit(status = 1L) })
